# Generated by Django 5.1.1 on 2024-09-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_lists_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lists',
            options={'managed': False},
        ),
    ]
