# Generated by Django 5.1.1 on 2024-09-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signed_in',
            field=models.BooleanField(default=False),
        ),
    ]
