# Generated by Django 5.1.1 on 2024-10-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_lists_options'),
        ('base', '0004_user_signed_in'),
    ]

    operations = [
    ]
