# Generated by Django 5.1.1 on 2024-10-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_merge_0003_alter_lists_options_0004_user_signed_in'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
