# Generated by Django 5.1.1 on 2024-10-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_item_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
