# Generated by Django 5.1.1 on 2024-09-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('user_id', models.IntegerField()),
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'lists',
                'managed': False,
            },
        ),
    ]
