# Generated by Django 5.1.1 on 2024-09-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
